using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace M05JellyBellyJustinBarr
{
    public partial class CategoryForm : Form
    {
        // Declaration of a readonly field db of type JBModel
        private readonly JBModel db;

        // Constructor for CategoryForm
        public CategoryForm()
        {
            // Initializes the components of the form (typically generated by the form designer)
            InitializeComponent();

            // Instantiates a new JBModel and assigns it to the readonly field db
            db = new JBModel();
        }

        // Event handler for the load event of the CategoryForm
        private void CategoryForm_Load(object sender, EventArgs e)
        {
            // Adds two columns to the ListView lvCategory with headers "Category" and "Total"
            lvCategory.Columns.Add("Category");
            lvCategory.Columns.Add("Total");

            // Groups JellyBellies by category and calculates the count for each category
            var jbCat = db.JellyBellies.GroupBy(c => c.category).Select(cat => new CatTotals { Category = cat.Key, Total = cat.Count() });

            // Iterates through the CatTotals and adds them as items to the ListView
            foreach (CatTotals ct in jbCat)
            {
                // Creates an array of strings with the category and total values
                String[] listValues = { ct.Category, ct.Total.ToString() };

                // Creates a new ListViewItem with the array of values
                ListViewItem lvi = new ListViewItem(listValues);

                // Adds the ListViewItem to the lvCategory ListView
                lvCategory.Items.Add(lvi);
            }

            // Auto-resizes the columns of the lvCategory ListView
            lvCategory.AutoResizeColumn(0, ColumnHeaderAutoResizeStyle.ColumnContent);
            lvCategory.AutoResizeColumn(1, ColumnHeaderAutoResizeStyle.HeaderSize);
        }

        // Definition of the CatTotals class
        public class CatTotals
        {
            // Property for storing the category name
            public string Category { get; set; }

            // Property for storing the total count for the category
            public int Total { get; set; }
        }

        // Event handler for the "Close" button click
        private void BTNClose_Click(object sender, EventArgs e)
        {
            // Closes the CategoryForm
            Close();
        }

    }
}