using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace M05JellyBellyJustinBarr
{
    public partial class JellyBellyCentral : Form
    {
        // Constructor for JellyBellyCentral form
        public JellyBellyCentral()
        {
            // Initializes the components of the form (typically generated by the form designer)
            InitializeComponent();
        }

        // Event handler for the "Search Flavors" button click
        private void BTNSearchFlavors_Click(object sender, EventArgs e)
        {
            // Creates an instance of the JellyBellyForm
            JellyBellyForm jellyBellyForm = new JellyBellyForm();

            // Shows the JellyBellyForm as a modal dialog
            jellyBellyForm.ShowDialog();
        }

        // Event handler for the "Show Categories" button click
        private void BTNShowCats_Click(object sender, EventArgs e)
        {
            // Creates an instance of the CategoryForm
            CategoryForm catForm = new CategoryForm();

            // Shows the CategoryForm as a modal dialog
            catForm.ShowDialog();
        }

        // Event handler for the "Close" button click
        private void BTNClose_Click(object sender, EventArgs e)
        {
            // Closes the JellyBellyCentral form
            Close();
        }
    }
}
